### ISSUE TITLE
Estimated size of a full mirror?

### ISSUE THREAD

**Issue by darkonejr** [LOLINTERNETZ/vscodeoffline#1]
Hey, thanks for creating this... wondering how big is the full vscode mirror currently?  Just trying to ballpark how much space I would need if I went the syncall route...

**Comment by LOLINTERNETZ** [comment]
Hey, no problems at all. Sorry for my delay responding too as I hadn't realised this comment was against my repo... 

Going down the syncall route is around 30GB for a single snapshot, but obviously this would grow over time as there is not cleanup functionality at the moment. I'll add this to the README. Thanks
