### ISSUE TITLE
Adding CI to the repo

### ISSUE THREAD

**Issue by assafushy** [LOLINTERNETZ/vscodeoffline#11]
hi man,
you want me to add ci to this repo?

**Comment by LOLINTERNETZ** [comment]
Hi @assafushy absolutely, yes! I had always envisioned adding support, but never got around to it :) Thanks

**Comment by assafushy** [comment]
Hi @LOLINTERNETZ ,

i dont see a github actions pipeline currently running.

if you want as a basic start solution i will create an action pipeline to build and publish the 2 images on master updates.
from there you will be able to open tickets for me to do whatever you think is needed.

ok by you?

**Comment by LOLINTERNETZ** [comment]
Thanks @assafushy. I've finally added the actions pipeline, after Docker removed autobuilding for free accounts.
