### ISSUE TITLE
Multi-platform extensions not supported

### ISSUE THREAD

**Issue by k-jingyang** [LOLINTERNETZ/vscodeoffline#24]
Hey, thanks for making this :smiley: 

I realised that the current implementation doesn't seem to support extensions that differ across platforms. One such example would be [`redhat.java`](https://marketplace.visualstudio.com/items?itemName=redhat.java)

POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery returns something like this for `redhat.java`

![image](https://user-images.githubusercontent.com/3762963/158724135-a3b6c913-480a-4355-9fa9-30792b85e984.png)

**Comment by LOLINTERNETZ** [comment]
Should be fixed in the just released 1.0.21. Feel free to re-open if needed.
