### ISSUE TITLE
Managing sync diff

### ISSUE THREAD

**Issue by assafushy** [LOLINTERNETZ/vscodeoffline#29]
HI,
I am using the offline gallery and it's great.
 but I have a missing feature - "sync diff only" -- when I want to import and update since the last sync to my air-gapped network. I have to sync all.

I have no problem making the feature myself ->  are you accepting PR's?

**Comment by LOLINTERNETZ** [comment]
Hey! Yes absolutely - feel free to open a PR.

If I recall, the diff vs incremental was roughly in the hands of the
diode/air-gap implementation as it's just writing to disk and mtime
changing.

:-)
