### ISSUE TITLE
error while fetching extensions xhr failed

### ISSUE THREAD

**Issue by rondo10** [LOLINTERNETZ/vscodeoffline#32]
Hey, I get this error and I don't know how to handle it.
I get it when I search for any extension.
```error while fetching extensions xhr failed```

![image](https://user-images.githubusercontent.com/68192760/171061615-dda4bc3d-ab02-4e02-aa95-9fffec76f778.png)

**Comment by glevy** [comment]
2. Sort out SSL/TLS within your environment to support offline use.

Either create a certificate which is signed for the above domains, and is trusted by the clients; or
Deploy the bundled root and intermediate certificate authority (vscoffline/vscgallery/ssl/ca.crt and ia.crt), with the obvious security tradeoff.
Windows 10: Import the certificates into the machine's trusted root certificate authority (Start > "Manage Computer Certificates").

Darwin: Import the certificates into the machine's trusted root certificate authority.

Ubuntu: Easiest method seems to be Open Chrome, navigate to chrome://settings/certificates, select authorities and add the certificates.

**Comment by tomer953** [comment]
From the readme:

4. Using Chrome navigate to https://update.code.visualstudio.com/. You should **not see any certificate warnings**, if you do it's unlikely to work in VS Code.

**Comment by LOLINTERNETZ** [comment]
This appears to be fixed, let me know if there's something else going on
