### ISSUE TITLE
New feature: Support for Visual Studio

### ISSUE THREAD

**Issue by tomer953** [LOLINTERNETZ/vscodeoffline#39]
Hi,

since the Visual Studio using the same marketplace and almost the same vsix manifest, I think it should be achievable to sync the VS gallery as well. 

Thoughts?

**Comment by tomer953** [comment]
ok, so after some investigation -

- visual studio has an option to open private gallery, all you need is a folder with VSIX files, and then create some .xml   useful tutorial here: https://devblogs.microsoft.com/visualstudio/create-a-private-gallery-for-self-hosted-visual-studio-extensions/
- if we want to override the default store, we also need to register the `go.microsoft.com` DNS since the VS store making some request to this endpoint before making request to the marketplace endpoint (that already registered in current implementation)
- However, the following DNS record is not that easy to register, since the `hosts` file cannot accept it (windows bypass this specific domain), and we need to install custom DNS server for developing that feature

Personally I'm going to modify the code just to fetch the top N .vsix files from the store:
for example changing the query: https://github.com/tomer953/vscodeoffline/blob/visual-studio/vscoffline/sync.py#L428
and some other lines releated.
then create a private store based on the above tutorial for my org.

**Comment by LOLINTERNETZ** [comment]
I think this would be a great idea, being able to sync VS marketplace extensions. What works well for this codebase is being able to set it up once, and have a bunch of devs simply being able to consume extensions as they normally would. Anything to reduce friction in restrictive environments helps right?!
