### ISSUE TITLE
Support for previous versions of extensions?

### ISSUE THREAD

**Issue by almostjulian** [LOLINTERNETZ/vscodeoffline#4]
Looks like some extensions get tied to a insider version,  if you're running an offline gallery that is stable only, that presents a problem.. Stable VSCode will request the latest version that is insider only, reject that, but then VSCode can't download the previous version since the offline gallery only supports the current version.   A good example of this is the WSL extension for remote development, the current version requires VSCode 1.38 (which is insider only)...

**Comment by LOLINTERNETZ** [comment]
Ok, so this may resolve the issue but I need a few extensions to update to check...

**Comment by darkonejr** [comment]
The remote development extensions often wind up in this state if you are looking for something to test.

**Comment by LOLINTERNETZ** [comment]
As far as I know, this was fixed up
