### ISSUE TITLE
Error while fetching extensions. XHR failed

### ISSUE THREAD

**Issue by jmorcate** [LOLINTERNETZ/vscodeoffline#43]
Hi, 
I have tried to use vscgallery and, although I could download extensions and installers with vscsync, I don't get my RECOMENDED extension list populated. When I try to search for an extension, I get the following error:
```
Error while fetching extensions. XHR failed
```
I don't see any requests or error messages in the logs. I am using the provided certificates.

In fact, I don't know well what to expect. I am in an air-gapped network and I  would like to have the same experience as I was connected to the internet.

**Comment by LOLINTERNETZ** [comment]
On your airgapped network, can you pop open a web browser and navigate to https://update.code.visualstudio.com/ without any connection errors or certificate warnings?

In the vscode output window, do you see any extension related problems?

<img width="212" alt="image" src="https://user-images.githubusercontent.com/49271015/198904038-c8844c79-3483-4ff8-83d7-c50a6335e7b4.png">

Finally, check Help > Toggle Development Tools > Select Network Tab > Select Extensions in vscode, do you see any fetch errors. Should look like this if working successfully.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/49271015/198904116-37e3d882-a391-4066-a3d9-511ef19cffc9.png">

**Comment by GH0st3rs** [comment]
I got the same problem. I can open the url in my firefox without any warnings. But In vscode debug console I got an error:
```
net::ERR_CERT_AUTHORITY_INVALID
```

**Comment by tomer953** [comment]
> I got the same problem. I can open the url in my firefox without any warnings. But In vscode debug console I got an error:
> 
> ```
> net::ERR_CERT_AUTHORITY_INVALID
> ```

which os do you use?

**Comment by GH0st3rs** [comment]
> which os do you use?

Never mind I found solution (11) https://askubuntu.com/questions/244582/add-certificate-authorities-system-wide-on-firefox
And just replaced `libnssckbi.so` to `p11-kit-trust.so`. After restart the vscode is became to see the systems certificates. 
The problem been that Firefox used separated certificate storage than vscode
